Move auto select panel to only when in script
dugramen/godot-script-dock pull request #1
Opened 2024-07-14 19:11 UTC by CollinViz

Changed that the Script tab is only active when you are in script manage.
I found it a pain to keep swapping to scene tree when I open scene with scripts.

Also update the addons/script-dock/plugin.cfg

2024-07-15 19:58 UTC, dugramen commented
Sounds good. I didn't really know the best way to do auto switch, so this might be better. I'll have to test it later though

2024-07-16 22:05 UTC, dugramen requested changes
Just a few changes before I merge. Thanks for contributing!

2024-07-16 22:05 UTC, dugramen commented on addons/script-dock/plugin.gd
>  	script_editor.editor_script_changed.connect(on_script_changed)
```suggestion
	script_editor.editor_script_changed.connect(script_visibility_changed)
```
`on_script_changed`'s code was moved to `script_visibility_changed`, so the signal should connect to that

2024-07-16 22:05 UTC, dugramen commented on addons/script-dock/plugin.gd
> +func script_visibility_changed():
```suggestion
func script_visibility_changed(a = null):
	if !script_editor.is_visible_in_tree():
		return
```
Currently, leaving from the `Script` view to another view like `Node2D`, causes the script dock to be selected again. It should check if the script editor is visible first

The `a = null` parameter is just so it can also handle the `script_changed` signal without erroring

2024-07-16 22:05 UTC, dugramen commented on addons/script-dock/plugin.gd
> +
```suggestion
```
This function doesn't do anything anymore, so we can remove it

2024-07-16 22:05 UTC, dugramen commented on addons/script-dock/plugin.cfg
> +author="Koliur Rahman"
😅 I forget my real name is on github. I think just my username is ok
```suggestion
author="dugramen"
```

2024-07-18 05:36 UTC, CollinViz commented
Cool - please approve

2024-07-18 15:13 UTC, merged

2024-07-18 15:15 UTC, dugramen commented
Thanks again! The changes should appear on the asset library in a few days